<script type="text/javascript" src="<?php echo base_url(); ?>main_assets/landing_page_asset/assets/js/jquery.min.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>main_assets/landing_page_asset/assets/js/tether.min.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>main_assets/landing_page_asset/assets/js/bootstrap.min.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>main_assets/landing_page_asset/assets/js/bootstrap-hover-dropdown.min.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>main_assets/landing_page_asset/assets/js/owl.carousel.min.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>main_assets/landing_page_asset/assets/js/echo.min.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>main_assets/landing_page_asset/assets/js/wow.min.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>main_assets/landing_page_asset/assets/js/jquery.easing.min.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>main_assets/landing_page_asset/assets/js/jquery.waypoints.min.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>main_assets/landing_page_asset/assets/js/electro.js"></script>
